suite: test secret

templates:
  - secret.yaml

tests:
  - it: should not set open id environment variables when open id is not available
    set:
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: password
        allowedLoginMethods:
          - password
          - openid
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.1.0
    asserts:
      - hasDocuments:
          count: 0

  - it: should not set open id environment variables when ingress is not enabled
    set:
      ingress:
        enabled: false
      login:
        method: openid
        allowedLoginMethods:
          - password
          - openid
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.1.0
    asserts:
      - hasDocuments:
          count: 0

  - it: should not set open id environment variables when openid is not allowed
    set:
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: openid
        allowedLoginMethods:
          - password
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.1.0
    asserts:
      - hasDocuments:
          count: 0

  - it: should not set open id environment variables when app version is less than 25.1.0 from image tag
    set:
      image:
        tag: 25.0.0
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: openid
        allowedLoginMethods:
          - openid
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    asserts:
      - hasDocuments:
          count: 0

  - it: should not set open id environment variables when app version is less than 25.1.0 from chart app version
    set:
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: openid
        allowedLoginMethods:
          - openid
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.0.0
    asserts:
      - hasDocuments:
          count: 0

  - it: should set open id environment variables when open id is available and dicovertUrl is set and clientId is set and clientSecret is set
    set:
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: "openid"
        allowedLoginMethods:
          - openid
        openid:
          enforce: false
          providerName: "Fake Provider"
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.1.0
    asserts:
      - equal:
          path: data.ACTUAL_MULTIUSER
          value: "true"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_ENFORCE
          value: "false"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_PROVIDER_NAME
          value: "Fake Provider"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_CLIENT_ID
          value: "openid-client-id"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_CLIENT_SECRET
          value: "openid-client-secret"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_DISCOVERY_URL
          value: "https://openid.com/.well-known/openid-configuration"
          decodeBase64: true

  - it: should set open id environment variables when open id is available and authorizationEndpoint is set and tokenEndpoint is set and userInfoEndpoint is set and clientId is set and clientSecret is set
    set:
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: "openid"
        allowedLoginMethods:
          - openid
        openid:
          enforce: false
          providerName: "Fake Provider"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
          authorizationEndpoint: "https://openid.com/authorize"
          tokenEndpoint: "https://openid.com/token"
          userInfoEndpoint: "https://openid.com/userinfo"
    chart:
      appVersion: 25.1.0
    asserts:
      - equal:
          path: data.ACTUAL_MULTIUSER
          value: "true"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_ENFORCE
          value: "false"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_PROVIDER_NAME
          value: "Fake Provider"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_CLIENT_ID
          value: "openid-client-id"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_CLIENT_SECRET
          value: "openid-client-secret"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_AUTHORIZATION_ENDPOINT
          value: "https://openid.com/authorize"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_TOKEN_ENDPOINT
          value: "https://openid.com/token"
          decodeBase64: true
      - equal:
          path: data.ACTUAL_OPENID_USERINFO_ENDPOINT
          value: "https://openid.com/userinfo"
          decodeBase64: true

  - it: should set http actual server hostname environment variable when ingress is enabled
    set:
      ingress:
        enabled: true
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: "openid"
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.1.0
    asserts:
      - equal:
          path: data.ACTUAL_OPENID_SERVER_HOSTNAME
          value: "http://actualbudget.local"
          decodeBase64: true

  - it: should set https actual server hostname environment variable when ingress is enabled and tls is set
    set:
      ingress:
        enabled: true
        tls:
          - hosts:
              - actualbudget.local
            secretName: actualbudget-tls
        hosts:
          - host: actualbudget.local
            paths:
              - path: /
                pathType: ImplementationSpecific
      login:
        method: "openid"
        openid:
          dicovertUrl: "https://openid.com/.well-known/openid-configuration"
          clientId: "openid-client-id"
          clientSecret: "openid-client-secret"
    chart:
      appVersion: 25.1.0
    asserts:
      - equal:
          path: data.ACTUAL_OPENID_SERVER_HOSTNAME
          value: "https://actualbudget.local"
          decodeBase64: true
