{{- if and (eq .Values.db.type "postgresdb") (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.postgresql.fullname" . }}
  labels:
    app: {{ include "n8n.name" . }}
    chart: {{ include "n8n.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres-password: {{ .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}
{{- if eq .Values.existingEncryptionKeySecret "" }}
{{- $secretName := printf "%s-encryption-key-secret" (include "n8n.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $encryptionKey := "" }}
{{- if $existingSecret }}
{{- $encryptionKey = index $existingSecret.data "N8N_ENCRYPTION_KEY" | b64dec }}
{{- else }}
{{- $encryptionKey = ternary .Values.encryptionKey (include "n8n.generateRandomHex" 32) (ne .Values.encryptionKey "") }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "n8n.name" . }}
    chart: {{ include "n8n.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "argocd.argoproj.io/sync-options": "Prune=false"
type: Opaque
data:
  N8N_ENCRYPTION_KEY: {{ $encryptionKey | b64enc | quote }}
{{- end }}
{{- if and (eq .Values.worker.mode "queue") (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.redis.fullname" . }}
  labels:
    app: {{ include "n8n.name" . }}
    chart: {{ include "n8n.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  redis-username: {{ .Values.externalRedis.username | default "default" | b64enc | quote }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
{{- if eq .Values.taskRunners.mode "external" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "n8n.taskRunners.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "n8n.name" . }}
    chart: {{ include "n8n.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  auth-token: {{ default (include "n8n.generateRandomHex" 32) .Values.taskRunners.external.mainNodeAuthToken | b64enc | quote }}
  worker-auth-token: {{ default (include "n8n.generateRandomHex" 32) .Values.taskRunners.external.workerNodeAuthToken | b64enc | quote }}
{{- end }}
